export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CLEAR_CONTACT_STATE = 'CLEAR_CONTACT_STATE';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const SET_FATAL_ERROR = 'SET_FATAL_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


